### ISSUE TITLE
Fix blink of content on first scroll sometimes

### ISSUE THREAD

**Issue by ajoslin** [ajoslin/angular-scrolly#5]

**Comment by ajoslin** [comment]
First reproducable here: http://run.plnkr.co/plunks/mAjARz/#/angebot/gv3

Need to narrow down to smaller case and fix, or just find the bug

**Comment by tbosch** [comment]
On which device?
I heard that Android shows a blink when first adding a `translate` to an element, as it then gets pushed to the cpu...

**Comment by ajoslin** [comment]
Ah right, I remember I already fixed this lol :-)

http://ajoslin.github.io/angular-scrolly/#/guide/gotchas

**Comment by ajoslin** [comment]
Need to add backface-visibility: none to scrollable elements

**Comment by artworkad** [comment]
hm this is not fixed for me. On android the scroll pane blinks on first scroll.

When I drag the pane up first time after view loaded, the pane does not respond, the pane blinks and after a second the pane jumps up. I tried it with the gotchas however they did not help.

Any ideas?

**Comment by ajoslin** [comment]
Does it blink on the demo site?

On Thursday, August 8, 2013, ArtworkAD wrote:

> hm this is not fixed for me. On android the scroll pane blinks on first
> scroll.
> 
> When I drag the pane up first time after view loaded, the pane does not
> respond, the pane blinks and after a second the pane jumps up. I tried it
> with the gotchas however they did not help.
> 
> Any ideas?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ajoslin/angular-scrolly/issues/5#issuecomment-22317282
> .

## 

...sent from my iPhone

**Comment by artworkad** [comment]
@ajoslin hm actually not. I have to digg more into this :yum:

**Comment by ajoslin** [comment]
Be sure you have -webkit-backface-visibility:none; applying to the container that is scrolling.

**Comment by artworkad** [comment]
Ok I fixed the blinking. However there seems to be a noticeable dragging delay, the container is animated 1-2 seconds after dragging it.
